In [23]:
# ======================================== Acknowledgement ================================================
# This is part of series of work to translate Dr.Daniel Mckenzie's LsqClusterPursuit code from MatLab into 
# Python; The purpose of this project is first to understand how the algorithm works and second to practice 
# coding ability in python language;

In [49]:
import numpy as np
import math
from scipy.sparse.linalg import lsqr

In [52]:
def LsqClusterPursuit(L: np.ndarray, Gamma_a: np.ndarray, Omega_a: np.ndarray, n_a: int, reject: float):

    # Inputs:
    # L ........................................... Laplacian matrix
    # Gamma_a ..................................... Labeled data for C_a
    # Omega_a ..................................... Superset containing C_a
    # n_a ......................................... (Estimated) size of C_a

    # Outputs:
    # C ........................................... Estimate of C_a (including Gamma_a)
    # v ........................................... vector of probabilities of not being in C
    
    Phi = L[:, Omega_a]                             # Keep columns of L with indices in Omega_a
    n = len(L)                                      # Number of vertices in graph
    vdeg = Phi.sum(axis=1)                          # Get the vector of vertex degrees
    k = math.floor(n_a/5)
    indices = np.argpartition(Phi, k)[:k]
    Phi[:, indices] = 0
    g = len(Gamma_a)
    h = len(Omega_a)
    sparsity = math.ceil(1.1*h - (n_a - g))
    if sparsity <= 0:
        C = Omega_a | Gamma_a
        v = np.zeros((n,1))
    else:
        v = lsqr(Phi, vdeg)[0]
        Lambda_a = []
        for i in range(len(v)):
            if v[i] > reject:
                Lambda_a += [i] 
    #    print(Lambda_a) 
        B = np.concatenate([np.setdiff1d(Omega_a, Omega_a[Lambda_a]), np.setdiff1d(Omega_a[Lambda_a], Omega_a)])        
        C = np.union1d(B, Gamma_a)
    return C, v



In [53]:
P = np.array([
    [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 1, 1, 0]
])

Gamma_a = np.array([0,1,2,3])
Omega_a = np.array([0,1,2,3,6,9])
print(P)
print(LsqClusterPursuit(P, Gamma_a, Omega_a, 4, .1))


[[0 1 1 1 0 0 0 0 0 0]
 [1 0 1 1 0 0 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 1 1 0]]
(array([0, 1, 2, 3]), array([1., 1., 1., 1., 1., 1.]))


In [11]:
P = np.array([
    [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 1, 1, 0]
])

vd = P.sum(axis=1)
x = lsqr(P, vd)[0]

print(vd)
print(x)
print(x[[1,2,3]])


[3 3 3 3 2 2 2 2 2 2]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1.]


In [35]:
lst = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
xlst = lst[[0, 1, 2]]
print(xlst)
print(type(xlst))

[1 2 3]
<class 'numpy.ndarray'>
